name: livekit_example
description: Example app that uses LiveKit Flutter SDK
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  device_info_plus: ^9.0.3
  flutter_background: ^1.1.0
  provider: ^6.0.1
  logging: ^1.0.1
  shared_preferences: ^2.0.7
  google_fonts: ^4.0.4
  eva_icons_flutter: ^3.0.0
  flutter_svg: ^1.0.0
  livekit_client: ^1.2.1
  http:
  record: ^4.4.4
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  socket_io_client: ^2.0.3+1
  audioplayers: ^5.1.0
  wakelock_plus: ^1.1.1
  lottie: 2.6.0
  audio_session: 0.1.16
  just_audio: 0.9.35
  dart_ipify: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - images/logo-dark.svg
    - images/mic_lottie.json
